annual_salary = float(input('Enter your annual salary: '))
percent_of_salary = float(input('Enter the percent of your salary to save, as a decimal: '))
total_cost = float(input('Enter the cost of your dream home: '))
print (annual_salary)
print (percent_of_salary)
print (total_cost)
